### ISSUE TITLE
Neverball on Retina/Mavericks Interpreted as obsolete PowerPC Platform

### ISSUE THREAD

**Issue by dsoprea** [Neverball/neverball#93] opened 2014-08-26 20:53 UTC
I just downloaded 1.5.3 (the latest version available for a Mac), opened the DMG, clicked "Install", and got this dialog box:

![screen shot 2014-08-26 at 4 51 54 pm](https://cloud.githubusercontent.com/assets/715626/4051593/fd020a80-2d62-11e4-9b45-0b1e443f6e99.png)

It looks like it's not packaged properly (the application name is empty).

**Comment by xif-fr** [comment] 2019-06-16 17:34
Duplicate of #151

**Comment by parasti** [comment] 2019-06-17 04:33
Closing this since there is more progress in the other one.

**Closed by parasti** 2019-06-17 04:33 UTC
Labels: macosx
