### ISSUE TITLE
.config/neverball should be preferred for the config

### ISSUE THREAD

**Issue by albertvaka** [Neverball/neverball#356] opened 2024-01-24 16:50 UTC
Following nowadays conventions, the config files should be in `~/.config/neverball`. For backwards compatibility we can still read from `~/.neverball` if it exists, but if we have to create a new directory we should prefer `~/.config/neverball`.

**Comment by parasti** [comment] 2024-01-24 20:37
Duplicate of #238

**Closed by parasti** 2024-01-24 20:37 UTC
